// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noser_Fitness.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noser_Fitness.Infrastructure.Migrations
{
    [DbContext(typeof(NoserFitnessDbContext))]
    [Migration("20260113125015_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Noser_Fitness.Domain.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Attendee");
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CourseType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<int?>("InvitationsValidBeforeInHours")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7e2c4a9-3f6d-4c8e-9a1b-2d5f7c0e4a10"),
                            CourseType = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByMemberId = new Guid("7c9c9f51-6b2c-4f89-b5d4-1b4c8e2a1a01"),
                            InvitationsValidBeforeInHours = 24,
                            Location = "Main Gym",
                            MaxAttendees = 20,
                            Name = "Morning Fitness",
                            ScheduledAtUtc = new DateTime(2026, 3, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2a9e5b1-7d3f-4b8c-9e6a-1f0d4c2b5e11"),
                            CourseType = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByMemberId = new Guid("a3f8d7c4-9e21-4c1f-b6e2-8d3c5b7a4f02"),
                            InvitationsValidBeforeInHours = 12,
                            Location = "Studio A",
                            MaxAttendees = 1,
                            Name = "Trial Workout",
                            ScheduledAtUtc = new DateTime(2026, 3, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f9a1c5e2-4b7d-4e6a-8c3f-0d1b2a9e7c12"),
                            CourseType = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByMemberId = new Guid("e1b4c9a2-6d5f-4a88-9e3b-2f7c8d1a0b03"),
                            InvitationsValidBeforeInHours = 48,
                            Location = "Cycling Room",
                            MaxAttendees = 50,
                            Name = "Indoor Cycling Blast",
                            ScheduledAtUtc = new DateTime(2026, 3, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "State", "Noser_Fitness.Domain.Invitation.State#InvitationStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("ModifiedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Invitation");
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c9c9f51-6b2c-4f89-b5d4-1b4c8e2a1a01"),
                            Email = "john.doe@example.com",
                            Firstname = "John",
                            Lastname = "Doe"
                        },
                        new
                        {
                            Id = new Guid("a3f8d7c4-9e21-4c1f-b6e2-8d3c5b7a4f02"),
                            Email = "jane.smith@example.com",
                            Firstname = "Jane",
                            Lastname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("e1b4c9a2-6d5f-4a88-9e3b-2f7c8d1a0b03"),
                            Email = "alex.miller@example.com",
                            Firstname = "Alex",
                            Lastname = "Miller"
                        });
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Attendee", b =>
                {
                    b.HasOne("Noser_Fitness.Domain.Course", null)
                        .WithMany("Attendees")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Invitation", b =>
                {
                    b.HasOne("Noser_Fitness.Domain.Course", null)
                        .WithMany("Invitations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noser_Fitness.Domain.Course", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
